{{if .Values.resync.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  schedule: {{ .Values.resync.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Release.Name | quote }}
            app.kubernetes.io/instance: {{ .Release.Name | quote }}
        spec:
          containers:
            - name: {{ .Release.Name | quote }}
              image: "{{ .Values.resync.image.repository }}/{{ .Values.resync.image.name }}:{{ .Values.resync.image.tag }}"
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              env:
                - name: LOG_LEVEL
                  value: "{{ .Values.resync.logLevel }}"
                - name: BASE_URL
                  value: "{{ .Values.resync.baseUrl }}"
              envFrom:
                - secretRef:
                    name: "{{ .Release.Name }}-pwd"
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-pwd"
  labels:
    {{- include "dtrack-job.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ .Values.resync.password | quote }}
  {{- end }}