apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}"
spec:
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: dependencytrack
  podSelector:
    matchLabels:
      {{- include "dtrack-job.selectorLabels" . | nindent 4 }}
  policyTypes:
    - Egress